name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.4
  - scipy=0.18
  - mkl=2017.0.3
  - netCDF4
  - xarray
  - dask
  - distributed
  - pytest
  - future
  - matplotlib
  - ipython
  - pip:
    - coveralls
    - pytest-cov
    - pytest-catchlog
    - runipy
