name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.5
  - scipy
  - netCDF4
  - xarray
  - dask
  - distributed
  - pytest
  - future
  - matplotlib
  - jupyter
  - flake8
  - pip:
    - coveralls
    - pytest-cov
    - pytest-catchlog
