name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - scipy
  - netCDF4
  - dask
  - distributed
  - pytest
  - future
  - matplotlib
  - jupyter
  - flake8
  - pip:
    - coveralls
    - pytest-cov
    - git+https://github.com/pydata/xarray.git
