name: test_env
channels:
  - conda-forge
dependencies:
  - python=2.7
  - scipy
  - netCDF4
  - xarray
  - dask
  - distributed
  - pytest
  - future
  - matplotlib
  - ipython
  - pip:
    - coveralls
    - pytest-cov
    - pytest-catchlog
    - runipy
