name: aospy-docs
channels:
  - conda-forge
dependencies:
  - python=3.6
  - sphinx=1.7.6
  - numpy=1.14.5
  - numpydoc=0.8.0
  - scipy=1.1.0
  - pandas=0.23.3
  - netCDF4=1.4.0
  - xarray=0.11.0
  - ipython=6.4.0
  - matplotlib=2.2.2
  - cftime=1.0.0